import { Visuals } from './visuals.js?v=drive-ground-v3';
import { terrainBaseHeight, terrainHeight } from './terrain.js';
const $=s=>document.querySelector(s),planets=[['AETHERIS','FERRITE ORE'],['DUSKARA','TITANIUM VEIN'],['KRYON','ALGAE DNA'],['NEBULON','LITHIUM CRYSTAL']];
let visual,selected=0,mode='cockpit',paused=false,input={},state,last=0,shotClock=0,bank={};
try{let b=JSON.parse(localStorage.tibertronV2Bank||'{}');if(b&&typeof b==='object'&&!Array.isArray(b))for(let[k,v]of Object.entries(b))if(typeof v==='number'&&Number.isFinite(v))bank[k]=v}catch{}
const clearInput=()=>input={},clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),active=()=>state.deposits[state.stop];
function cards(){let h=$('#planetCards');h.innerHTML=planets.map((p,i)=>`<button class="planet-card ${i===selected?'active':''}" data-p="${i}" style="--atlas-row:${i}"><b>${p[0]}</b><span>${p[1]}</span></button>`).join('');h.querySelectorAll('[data-p]').forEach(b=>b.onclick=()=>{selected=+b.dataset.p;cards();visual.cockpit(selected)});$('#cockpit').style.setProperty('--planet-row',selected);$('#selectedName').textContent=planets[selected][0];$('#selectedDetail').textContent=planets[selected][1]+' · PROCEDURAL SURFACE';$('#bankCargo').textContent=String(Object.values(bank).reduce((a,v)=>a+v,0));let d=$('#bankDetails');if(d)d.textContent=planets.map(([,r])=>`${r}: ${bank[r]||0}`).join(' · ')}
function fresh(){let deposits=[18,48,78].map((x,i)=>({x,initial:30,remaining:30,mined:0,lost:0,active:i===0})),rocks=[{x:8,hp:3,maxHp:3,size:'small'},{x:28,hp:5,maxHp:5,size:'large'},{x:58,hp:3,maxHp:3,size:'small'},{x:69,hp:5,maxHp:5,size:'large'}];return{mode:'landing',phase:'LANDING',landing:1,landingProgress:0,x:0,y:0,surface:terrainHeight(selected,0,rocks),vx:0,vy:0,driveDistance:0,health:6,invulnerable:0,time:0,cameraX:0,extractionX:null,deposits,craters:[{x:12,width:3},{x:34,width:3},{x:64,width:3}],rocks,enemies:[],projectiles:[],particles:[],stop:0,waveClock:2,launchProgress:0,notice:'LANDING SEQUENCE',noticeTime:2}}
function say(t,n=2){state.notice=t;state.noticeTime=n}function sync(){if(state)state.mode=state.phase.toLowerCase()}
function hud(){if(!state)return;let d=active();$('#cargo').textContent=`${Math.round(state.deposits.reduce((a,x)=>a+x.mined,0))} / 90`;$('#goal').textContent=state.phase==='EVAC'?'DRIVE TO EVAC PAD → 92':state.phase==='EXTRACT'?`EXTRACT STOP ${state.stop+1} · ${Math.ceil(d.remaining)} LEFT`:state.phase==='LANDING'?'LANDING SEQUENCE':`DRIVE TO STOP ${state.stop+1} GATE`;$('#health').textContent='◆'.repeat(state.health)+'◇'.repeat(6-state.health);$('#message').textContent=state.noticeTime>0?state.notice:''}
function cockpit(){clearInput();paused=false;mode='cockpit';state=null;$('#hud').classList.add('hidden');$('#pause').classList.add('hidden');$('#result').classList.add('hidden');$('#extract').classList.add('hidden');$('#cockpit').classList.remove('hidden');visual.cockpit(selected);cards()}
function start(){clearInput();state=fresh();mode='mission';paused=false;shotClock=0;sync();visual.mission(selected,state.deposits,state.craters,state.rocks);$('#cockpit').classList.add('hidden');$('#result').classList.add('hidden');$('#pause').classList.add('hidden');$('#hud').classList.remove('hidden');hud()}
function advance(){state.enemies=[];state.projectiles=[];active().active=false;if(state.stop<2){state.stop++;active().active=true;state.phase='DRIVE';state.extractionX=null;state.cameraX=state.x;say(`STOP ${state.stop+1} UNLOCKED`,3)}else{state.phase='EVAC';state.extractionX=null;state.cameraX=state.x;say('ALL CRYSTALS ACCOUNTED · EVACUATE',3)}sync()}
function hit(t){if(!state||mode!=='mission')return;if(t==='rover'){if(state.invulnerable>0)return;state.health--;state.invulnerable=1.1;say('ROVER HIT · SHIELD GRACE ACTIVE');if(state.health<=0){finish(false);return}}else{if(state.phase!=='EXTRACT')return;let d=active();if(d.remaining<=0)return;let loss=Math.min(3,d.remaining);d.remaining-=loss;d.lost+=loss;say('DEPOSIT HIT · DEFEND THE RIG');if(d.remaining<=0)advance()}hud()}
function spawn(){let d=active(),wave=Math.floor(state.time/5)%3,types=wave===2?['drone','crawler']:['scout','crawler'];for(let i=0;i<types.length;i++){let kind=types[i],air=kind!=='crawler',maxHp=kind==='drone'?5:kind==='crawler'?4:3;state.enemies.push({id:crypto.randomUUID(),kind,x:d.x+(i?2.25:1.2),homeX:d.x+(i?2.25:1.2),y:air?(kind==='drone'?3.35:2.8):1.08,hp:maxHp,maxHp,hitRadius:kind==='drone'?.92:kind==='crawler'?.78:.66,phase:Math.random()*Math.PI*2,speed:kind==='crawler'?.75:kind==='drone'?1.05:1.45,cooldown:1+i*.6});}say('ALIEN WAVE INBOUND',1.5)}
function shoot(up){if(mode!=='mission'||paused||state.phase==='LANDING'||shotClock>0)return;shotClock=.22;state.projectiles.push({id:crypto.randomUUID(),x:state.x+(up?.2:1.29),y:state.surface+state.y+(up?2.16:1.68),enemy:false,arc:!!up,vx:up?7.5:16,vy:up?5.5:0})}
function enemyShot(e){let d=active(),t=Math.random()<.45?{x:d.x,y:terrainHeight(selected,d.x,state.rocks)+.8}:{x:state.x,y:state.surface+state.y+1},dx=t.x-e.x,dy=t.y-e.y,l=Math.hypot(dx,dy)||1;state.projectiles.push({id:crypto.randomUUID(),x:e.x,y:e.y,enemy:true,vx:dx/l*8,vy:dy/l*8})}
function finish(ok){clearInput();if(!ok){mode='dead';state.phase='RESULT';sync();$('#resultTag').textContent='ROVER OFFLINE';$('#resultTitle').textContent='Recovery beacon sent.';$('#resultText').textContent='Cargo was not transferred.';$('#result').classList.remove('hidden');$('#hud').classList.add('hidden');return}state.phase='LAUNCH';state.launchProgress=0;say('EVAC SHIP DESCENDING',2);sync()}
function move(dt){let d=active(),dir=(input.left?-1:0)+(input.right?1:0),oldX=state.x,oldSurface=state.surface,recovered=false,distanceCounted=false,maxSpeed=6,approach=(v,target,rate)=>v+clamp(target-v,-rate*dt,rate*dt);if(dir){let rate=Math.sign(state.vx||dir)!==dir?34:24;state.vx=approach(state.vx,dir*maxSpeed,rate)}else state.vx=approach(state.vx,0,12);let attempted=state.vx*dt,nextX=clamp(oldX+attempted,-2,94);if(nextX!==oldX+attempted)state.vx=0;state.x=nextX;state.surface=terrainHeight(selected,state.x,state.rocks);if(input.jump&&state.y===0){state.vy=7.2;input.jump=false}state.vy-=18*dt;state.y+=state.vy*dt;if(state.y<=0){state.y=0;state.vy=0}let c=state.craters.find(c=>Math.abs(state.x-c.x)<c.width/2);if(c&&state.y<.1){hit('rover');if(mode!=='mission')return;state.x=oldX<c.x?c.x-c.width/2-.03:c.x+c.width/2+.03;state.vx=0;state.surface=terrainHeight(selected,state.x,state.rocks);state.y=0;recovered=true;say('CRATER RECOVERY · JUMP THE GAP')}for(let r of state.rocks)if(r.hp&&Math.abs(state.x-r.x)<.75&&state.y===0){state.x=oldX;state.vx=0;state.surface=oldSurface;say('ROCK BLOCKING ROUTE · FIRE TO BREAK');break}if(state.phase==='DRIVE'&&state.x>=d.x-2){state.phase='EXTRACT';state.extractionX=d.x;state.cameraX=state.x;let clamped=clamp(state.x,d.x-3,d.x+3);if(clamped!==state.x)state.vx=0;state.x=clamped;sync()}if(state.phase==='EXTRACT'){let clamped=clamp(state.x,d.x-3,d.x+3);if(clamped!==state.x)state.vx=0;state.x=clamped;state.surface=terrainHeight(selected,state.x,state.rocks);let inside=Math.abs(state.x-d.x)<1.4&&state.y===0;$('#extract').classList.toggle('hidden',!inside);if(!recovered){state.driveDistance+=state.x-oldX;distanceCounted=true}if(inside&&input.extract&&d.remaining>0){let v=Math.min(d.remaining,dt*5);d.remaining-=v;d.mined+=v;if(d.remaining<=0){advance();return}}$('#extractFill').style.width=inside?(d.mined/d.initial*100)+'%':'0%';if(!state.enemies.length&&state.waveClock<0){spawn();state.waveClock=5}state.waveClock-=dt}else $('#extract').classList.add('hidden');if(state.phase==='EVAC'&&state.x>=92)finish(true);if(!distanceCounted&&!recovered)state.driveDistance+=state.x-oldX}
function combat(dt){let d=active();for(let e of state.enemies){let offset=e.kind==='crawler'?Math.sin(state.time*e.speed+e.phase)*1.35:Math.sin(state.time*e.speed+e.phase)*2.15;e.x=clamp(e.homeX+offset,d.x-2.65,d.x+2.65);let ground=terrainHeight(selected,e.x,state.rocks);e.y=ground+(e.kind==='crawler'?1.08:(e.kind==='drone'?3.35:2.8)+Math.sin(state.time*(e.kind==='drone'?1.5:2.4)+e.phase)*.3);e.cooldown-=dt;if(e.cooldown<0){enemyShot(e);e.cooldown=1.8+Math.random()}}for(let i=state.projectiles.length-1;i>=0;i--){let p=state.projectiles[i];if(p.arc)p.vy-=5*dt;p.x+=p.vx*dt;p.y+=p.vy*dt;if(p.enemy){if(Math.abs(p.x-state.x)<.45&&Math.abs(p.y-(state.surface+state.y+1))<.6){hit('rover');state.projectiles.splice(i,1);if(mode!=='mission')return;continue}if(state.phase==='EXTRACT'&&d.remaining>0&&Math.abs(p.x-d.x)<.5&&Math.abs(p.y-(terrainHeight(selected,d.x,state.rocks)+.8))<1){state.projectiles.splice(i,1);hit('deposit');if(state.phase!=='EXTRACT'||mode!=='mission')return;continue}}else{let e=state.enemies.find(e=>Math.abs(e.x-p.x)<(e.hitRadius||.65)&&Math.abs(e.y-p.y)<(e.hitRadius||.65)),r=state.rocks.find(r=>{let h=r.size==='large'?2.0:1.55;return r.hp&&Math.abs(r.x-p.x)<(r.size==='large'?1.05:.72)&&p.y>=terrainBaseHeight(selected,r.x)&&p.y<terrainBaseHeight(selected,r.x)+h});if(e){if(--e.hp===0)state.enemies.splice(state.enemies.indexOf(e),1);state.projectiles.splice(i,1);continue}if(r){--r.hp;state.projectiles.splice(i,1);continue}}if(Math.abs(p.x-state.x)>38||p.y>16||p.y<-3)state.projectiles.splice(i,1)}}
function step(dt){if(!state||paused)return;if(state.phase==='LAUNCH'){state.launchProgress+=dt/3;if(state.launchProgress>=1){let k=planets[selected][1],got=Math.round(state.deposits.reduce((a,d)=>a+d.mined,0));bank[k]=(bank[k]||0)+got;try{localStorage.tibertronV2Bank=JSON.stringify(bank)}catch{}mode='result';state.phase='RESULT';sync();$('#resultTag').textContent='MISSION COMPLETE';$('#resultTitle').textContent='Cargo delivered.';$('#resultText').textContent=`${got} ${k} banked.`;$('#result').classList.remove('hidden');$('#hud').classList.add('hidden');cards()}return}if(mode!=='mission')return;state.time+=dt;shotClock=Math.max(0,shotClock-dt);if(input.fire)shoot(false);if(input.up)shoot(true);state.invulnerable=Math.max(0,state.invulnerable-dt);if(state.phase==='LANDING'){state.landing-=dt;state.landingProgress=clamp(1-state.landing,0,1);if(state.landing<=0){state.phase='DRIVE';state.landingProgress=1;say('DRIVE TO STOP 1 GATE',2);sync()}state.noticeTime-=dt;hud();return}move(dt);if(mode!=='mission'||state.phase==='LAUNCH'||state.phase==='RESULT')return;combat(dt);if(mode!=='mission')return;state.cameraX=state.phase==='EXTRACT'?state.extractionX:state.x;state.noticeTime-=dt;hud()}
function frame(t){let dt=Math.min(.035,(t-last)/1000||0);last=t;step(dt);if(state)sync();visual.update(state||{mode:'cockpit'},paused?0:dt);visual.render();requestAnimationFrame(frame)}
function setPause(v){if(!state||mode!=='mission'||state.phase==='RESULT')return;paused=v;clearInput();$('#pause').classList.toggle('hidden',!v)}
function bind(){$('#launch').onclick=start;$('#pauseBtn').onclick=()=>setPause(true);$('.resume').onclick=()=>setPause(false);document.querySelectorAll('.return').forEach(b=>b.onclick=cockpit);$('.replay').onclick=start;let gameplay=new Set(['a','d','w','e','f','x','arrowleft','arrowright','arrowup',' ']);addEventListener('keydown',e=>{let k=e.key.toLowerCase();if(gameplay.has(k))e.preventDefault();if(e.repeat&&[' ','w','arrowup','f','x'].includes(k))return;if(['a','arrowleft'].includes(k))input.left=1;if(['d','arrowright'].includes(k))input.right=1;if([' ','w','arrowup'].includes(k))input.jump=1;if(k==='e')input.extract=1;if(k==='f')input.fire=1;if(k==='x')input.up=1;if(k==='escape'){e.preventDefault();setPause(!paused)}});addEventListener('keyup',e=>{let k=e.key.toLowerCase();if(gameplay.has(k))e.preventDefault();if(['a','arrowleft'].includes(k))input.left=0;if(['d','arrowright'].includes(k))input.right=0;if([' ','w','arrowup'].includes(k))input.jump=0;if(k==='e')input.extract=0;if(k==='f')input.fire=0;if(k==='x')input.up=0});document.querySelectorAll('[data-key]').forEach(b=>{let k=b.dataset.key;b.onpointerdown=e=>{e.preventDefault();if(k==='jump'){if(!input.jump)input.jump=1}else input[k]=1};['pointerup','pointerleave','pointercancel'].forEach(n=>b.addEventListener(n,()=>input[k]=0))});addEventListener('blur',()=>setPause(true));addEventListener('resize',()=>visual.resize())}
visual=new Visuals($('#space'));cards();visual.cockpit(selected);bind();window.__tibertron={get state(){return structuredClone(state?{...state,paused,bank:{...bank},accounting:active().remaining+active().mined+active().lost}:{mode,bank:{...bank}})},debug:{start,step:dt=>step(dt),setX:x=>{if(state)state.x=x},setPosition:(x,y=state?.y)=>{if(state){state.x=x;state.y=y}},mine:v=>input.extract=!!v,damage:hit,shoot}};requestAnimationFrame(frame);

